version: '3'

services:
  postgres-db-1:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-1-data:/var/lib/postgresql/data

  postgres-db-2:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: db2
    ports:
      - "5433:5432"  # Using a different external port to avoid conflict
    volumes:
      - postgres-db-2-data:/var/lib/postgresql/data

  mysql-db-1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-1-data:/var/lib/mysql

  mysql-db-2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db2
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"  # Using a different external port to avoid conflict

volumes:
  postgres-db-1-data:
  postgres-db-2-data:
  mysql-db-1-data:
  mysql-db-2-data: